package com.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "domicilio")
public class Domicilio  {

	@DynamoDBHashKey(attributeName = "domicilioId")
	private String domicilioId;

	@DynamoDBAttribute(attributeName = "calle")
	private String calle;

	@DynamoDBAttribute(attributeName = "numero")
	private int numero;

	/*
	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_localidad")
	private Localidad localidad;
	 */
}
