package com.api.entities;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;


@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "libro")
public class Libro  {

	@DynamoDBHashKey(attributeName = "libroId")
	private String libroId;

	@DynamoDBAttribute(attributeName = "fecha")
	private int fecha;

	@DynamoDBAttribute(attributeName = "genero")
	private String genero;

	@DynamoDBAttribute(attributeName = "paginas")
	private int paginas;

	@DynamoDBAttribute(attributeName = "titulo")
	private String titulo;

	/*
	@ManyToMany(cascade = CascadeType.REFRESH)
	private List<Autor> autores = new ArrayList<>();
     */
}
